/**
 * SIH26069 — Cities Configuration
 * Pan-India National Weather Big Data Analytics Platform
 * Active Cities across all Indian zones with dedicated authentic landmark photography.
 */

export const ACTIVE_CITIES = [
  // ── West & Central Maharashtra ─────────────────────────────────
  {
    name: 'Mumbai',
    aliases: ['mumbai', 'bombay'],
    state: 'Maharashtra',
    zone: 'West',
    region: 'Konkan Coast',
    lat: 19.0760,
    lon: 72.8777,
    status: 'live',
    color: '#0284C7',
    photo: '/cities/mumbai.jpg',
    tagline: 'Gateway & Marine Drive',
    description: 'High-density urban precipitation, tidal surge & flash flood telemetry active.',
    weatherTypes: ['Monsoon Deluge', 'High Tide Surge', 'Urban Waterlogging'],
    sensors: '24 AWS Stations · 2 Radar Rings',
  },
  {
    name: 'Nagpur',
    aliases: ['nagpur'],
    state: 'Maharashtra',
    zone: 'Central',
    region: 'Vidarbha',
    lat: 21.1458,
    lon: 79.0882,
    status: 'live',
    color: '#EA580C',
    photo: '/cities/nagpur.jpg',
    tagline: 'Zero Mile & Deekshabhoomi',
    description: 'Extreme heatwave, high thermal stress & Nag river catchment telemetry active.',
    weatherTypes: ['Extreme Heatwave', 'Thermal Anomaly', 'Dust Thunderstorm'],
    sensors: '18 AWS Stations · 1 Doppler Radar',
  },
  {
    name: 'Nashik',
    aliases: ['nasik', 'nashik'],
    state: 'Maharashtra',
    zone: 'West',
    region: 'Northern Western Ghats',
    lat: 19.9975,
    lon: 73.7898,
    status: 'live',
    color: '#059669',
    photo: '/cities/nashik.jpg',
    tagline: 'Godavari Ghats & Trimbak',
    description: 'Thunderstorm, hailstorm & Godavari basin hydrology telemetry active.',
    weatherTypes: ['Ghats Rain', 'Hailstorm Alert', 'Godavari Discharge'],
    sensors: '14 AWS Stations · Micro-Barometer Grid',
  },
  {
    name: 'Pune',
    aliases: ['pune', 'poona'],
    state: 'Maharashtra',
    zone: 'West',
    region: 'Desh Plateau',
    lat: 18.5204,
    lon: 73.8567,
    status: 'live',
    color: '#7C3AED',
    photo: '/cities/pune.jpg',
    tagline: 'Shaniwar Wada & Deccan',
    description: 'Mula-Mutha river basin hydrology and Western Ghats squall line detection.',
    weatherTypes: ['Ghats Showers', 'Urban Runoff', 'Squall Lines'],
    sensors: '20 AWS Stations · Micro-Met Network',
  },
  // ── North India ────────────────────────────────────────────────
  {
    name: 'Delhi',
    aliases: ['delhi', 'new delhi', 'delhi ncr'],
    state: 'Delhi',
    zone: 'North',
    region: 'Northern Plains',
    lat: 28.6139,
    lon: 77.2090,
    status: 'live',
    color: '#DC2626',
    photo: '/cities/delhi.jpg',
    tagline: 'India Gate & Red Fort',
    description: 'Severe winter smog/fog, pre-monsoon dust storms & extreme summer heatwaves.',
    weatherTypes: ['Dense Fog', 'Dust Storm', 'Extreme Heatwave'],
    sensors: '32 AWS Stations · 3 Doppler Radars',
  },
  {
    name: 'Agra',
    aliases: ['agra'],
    state: 'Uttar Pradesh',
    zone: 'North',
    region: 'Yamuna River Basin',
    lat: 27.1767,
    lon: 78.0081,
    status: 'live',
    color: '#E11D48',
    photo: '/cities/agra.jpg',
    tagline: 'Taj Mahal & Agra Fort',
    description: 'Yamuna floodplain hydrology, summer hot winds (Loo) & winter radiation fog.',
    weatherTypes: ['Severe Heatwave', 'Winter Fog', 'Yamuna Flood Stage'],
    sensors: '14 AWS Stations · Agro-Met Station',
  },
  {
    name: 'Jaipur',
    aliases: ['jaipur'],
    state: 'Rajasthan',
    zone: 'North',
    region: 'Aravalli Range',
    lat: 26.9124,
    lon: 75.7873,
    status: 'live',
    color: '#D97706',
    photo: '/cities/jaipur.jpg',
    tagline: 'Hawa Mahal & Amber Fort',
    description: 'Arid thermal convection, dust storms & seasonal flash inundation.',
    weatherTypes: ['Heatwave Alert', 'Sandstorm Gale', 'Dry Convection'],
    sensors: '15 AWS Stations · Desert Radar Mesh',
  },
  {
    name: 'Lucknow',
    aliases: ['lucknow'],
    state: 'Uttar Pradesh',
    zone: 'North',
    region: 'Awadh Gangetic Plain',
    lat: 26.8467,
    lon: 80.9462,
    status: 'live',
    color: '#0891B2',
    photo: '/cities/lucknow.jpg',
    tagline: 'Rumi Darwaza & Imambara',
    description: 'Gomti basin flood tracking, dense winter fog & severe monsoon squalls.',
    weatherTypes: ['Monsoon Squall', 'Winter Dense Fog', 'Gangetic Rain'],
    sensors: '16 AWS Stations · Agro-Met Sensors',
  },
  {
    name: 'Varanasi',
    aliases: ['varanasi', 'banaras', 'kashi'],
    state: 'Uttar Pradesh',
    zone: 'North',
    region: 'Middle Gangetic Valley',
    lat: 25.3176,
    lon: 82.9739,
    status: 'live',
    color: '#B45309',
    photo: '/cities/varanasi.jpg',
    tagline: 'Ganges Riverfront Ghats',
    description: 'Ganges water level telemetry, humid heat index & seasonal thunderstorm cells.',
    weatherTypes: ['Ganges Flood Stage', 'Thunderstorm', 'Humid Heatwave'],
    sensors: '12 AWS Stations · River Sensor Buoys',
  },
  {
    name: 'Kanpur',
    aliases: ['kanpur', 'cawnpore'],
    state: 'Uttar Pradesh',
    zone: 'North',
    region: 'Central UP Plains',
    lat: 26.4499,
    lon: 80.3319,
    status: 'live',
    color: '#475569',
    photo: '/cities/kanpur.jpg',
    tagline: 'Industrial Ganges Plain',
    description: 'Air quality particulate tracking, winter radiation fog & monsoon rainfall.',
    weatherTypes: ['Inversion Fog', 'Monsoon Downpour', 'High Heat Index'],
    sensors: '14 AWS Stations · Ambient Sensor Grid',
  },
  {
    name: 'Chandigarh',
    aliases: ['chandigarh'],
    state: 'Chandigarh',
    zone: 'North',
    region: 'Shivalik Foothills',
    lat: 30.7333,
    lon: 76.7794,
    status: 'live',
    color: '#2563EB',
    photo: '/cities/chandigarh.jpg',
    tagline: 'Sukhna Lake & Shivaliks',
    description: 'Shivalik foothills cloudburst risk, hail storms & winter westerly disturbances.',
    weatherTypes: ['Western Disturbance', 'Hailstorms', 'Foothill Deluge'],
    sensors: '12 AWS Stations · Doppler Radar Link',
  },
  {
    name: 'Amritsar',
    aliases: ['amritsar'],
    state: 'Punjab',
    zone: 'North',
    region: 'Majha Plains',
    lat: 31.6340,
    lon: 74.8723,
    status: 'live',
    color: '#9333EA',
    photo: '/cities/amritsar.jpg',
    tagline: 'Golden Temple Heritage',
    description: 'Winter cold wave anomalies, dense zero-visibility fog & crop season rain.',
    weatherTypes: ['Cold Wave Alert', 'Dense Advection Fog', 'Wheat Belt Rain'],
    sensors: '10 AWS Stations · Agro-Met Station',
  },
  {
    name: 'Shimla',
    aliases: ['shimla', 'simla'],
    state: 'Himachal Pradesh',
    zone: 'North',
    region: 'Himalayan Ridge',
    lat: 31.1048,
    lon: 77.1734,
    status: 'live',
    color: '#0284C7',
    photo: '/cities/shimla.jpg',
    tagline: 'Himalayan Ridge & Snow',
    description: 'Mountain precipitation, landslide vulnerability & snowfall elevation telemetry.',
    weatherTypes: ['Mountain Squalls', 'Cloudburst Warning', 'Cold Ridge Vortex'],
    sensors: '8 High-Altitude Stations · Micro-Radar',
  },
  {
    name: 'Dehradun',
    aliases: ['dehradun', 'dehra doon'],
    state: 'Uttarakhand',
    zone: 'North',
    region: 'Doon Valley',
    lat: 30.3165,
    lon: 78.0322,
    status: 'live',
    color: '#059669',
    photo: '/cities/dehradun.jpg',
    tagline: 'Mussoorie Valley & FRI',
    description: 'Orographic heavy rainfall, flash flood early warning & Doon valley inversion.',
    weatherTypes: ['Heavy Orographic Rain', 'Flash Flood Threat', 'Valley Squalls'],
    sensors: '10 AWS Stations · Basin Stream Gauges',
  },
  {
    name: 'Srinagar',
    aliases: ['srinagar'],
    state: 'Jammu and Kashmir',
    zone: 'North',
    region: 'Kashmir Valley',
    lat: 34.0837,
    lon: 74.7973,
    status: 'live',
    color: '#0D9488',
    photo: '/cities/srinagar.jpg',
    tagline: 'Dal Lake & Alpine Valley',
    description: 'Jhelum river flood stage monitoring, sub-zero freeze alerts & winter storm fronts.',
    weatherTypes: ['Sub-Zero Freeze', 'Western Storm Front', 'Jhelum Hydrology'],
    sensors: '12 Alpine Stations · Cryosphere Grid',
  },
  // ── South India ────────────────────────────────────────────────
  {
    name: 'Bengaluru',
    aliases: ['bengaluru', 'bangalore'],
    state: 'Karnataka',
    zone: 'South',
    region: 'Deccan Plateau',
    lat: 12.9716,
    lon: 77.5946,
    status: 'live',
    color: '#10B981',
    photo: '/cities/bengaluru.jpg',
    tagline: 'Vidhana Soudha & Gardens',
    description: 'Convective thunderstorm clustering, micro-catchment urban waterlogging.',
    weatherTypes: ['Pre-Monsoon Convection', 'Urban Lake Surges', 'Localized Downpour'],
    sensors: '28 AWS Stations · 1 Doppler Radar',
  },
  {
    name: 'Chennai',
    aliases: ['chennai', 'madras'],
    state: 'Tamil Nadu',
    zone: 'South',
    region: 'Coromandel Coast',
    lat: 13.0827,
    lon: 80.2707,
    status: 'live',
    color: '#0284C7',
    photo: '/cities/chennai.jpg',
    tagline: 'Marina Beach & Shore',
    description: 'Northeast monsoon surge, coastal depression, cyclone landfalls & inundation.',
    weatherTypes: ['Northeast Monsoon', 'Cyclone Inundation', 'Coastal Depression'],
    sensors: '22 AWS Stations · 2 Doppler Radars',
  },
  {
    name: 'Hyderabad',
    aliases: ['hyderabad', 'secunderabad'],
    state: 'Telangana',
    zone: 'South',
    region: 'Telangana Plateau',
    lat: 17.3850,
    lon: 78.4867,
    status: 'live',
    color: '#F59E0B',
    photo: '/cities/hyderabad.jpg',
    tagline: 'Charminar & Golconda',
    description: 'Musi river basin runoff, intense pre-monsoon thundershowers & summer heat.',
    weatherTypes: ['Musi Basin Runoff', 'Flash Downpour', 'High Thermal Stress'],
    sensors: '20 AWS Stations · Micro-Met Network',
  },
  {
    name: 'Kochi',
    aliases: ['kochi', 'cochin'],
    state: 'Kerala',
    zone: 'South',
    region: 'Malabar Coast',
    lat: 9.9312,
    lon: 76.2673,
    status: 'live',
    color: '#06B6D4',
    photo: '/cities/kochi.jpg',
    tagline: 'Chinese Fishing Nets',
    description: 'Southwest monsoon onset monitoring, high coastal humidity & lagoon hydrology.',
    weatherTypes: ['Monsoon Onset Vortex', 'Coastal Gale', 'Tidal Backwater Surge'],
    sensors: '16 AWS Stations · Maritime Radar',
  },
  {
    name: 'Thiruvananthapuram',
    aliases: ['thiruvananthapuram', 'trivandrum'],
    state: 'Kerala',
    zone: 'South',
    region: 'Southern Malabar',
    lat: 8.5241,
    lon: 76.9366,
    status: 'live',
    color: '#059669',
    photo: '/cities/thiruvananthapuram.jpg',
    tagline: 'Padmanabha & Kovalam',
    description: 'First monsoon landfall telemetry, heavy squall lines & marine wind speeds.',
    weatherTypes: ['Monsoon Front Landfall', 'Coastal Squall', 'Heavy Tropical Rain'],
    sensors: '14 AWS Stations · Coastal Radar',
  },
  {
    name: 'Visakhapatnam',
    aliases: ['visakhapatnam', 'vizag'],
    state: 'Andhra Pradesh',
    zone: 'South',
    region: 'Eastern Sea Board',
    lat: 17.6868,
    lon: 83.2185,
    status: 'live',
    color: '#0284C7',
    photo: '/cities/visakhapatnam.jpg',
    tagline: 'RK Beach & Dolphin Nose',
    description: 'Bay of Bengal cyclone tracking, storm surge modeling & maritime gale telemetry.',
    weatherTypes: ['Cyclone Alert', 'Storm Surge Wave', 'Maritime Gale'],
    sensors: '18 AWS Stations · High-Power Radar',
  },
  {
    name: 'Vijayawada',
    aliases: ['vijayawada', 'bezawada'],
    state: 'Andhra Pradesh',
    zone: 'South',
    region: 'Krishna River Basin',
    lat: 16.5062,
    lon: 80.6480,
    status: 'live',
    color: '#E11D48',
    photo: '/cities/vijayawada.jpg',
    tagline: 'Prakasam Barrage Delta',
    description: 'Prakasam barrage discharge, high summer humidity index & thunderstorm squalls.',
    weatherTypes: ['Krishna River Flood', 'Extreme Humidity Heat', 'Delta Squalls'],
    sensors: '14 AWS Stations · River Telemetry',
  },
  {
    name: 'Coimbatore',
    aliases: ['coimbatore', 'kovai'],
    state: 'Tamil Nadu',
    zone: 'South',
    region: 'Palghat Gap Basin',
    lat: 11.0168,
    lon: 76.9558,
    status: 'live',
    color: '#16A34A',
    photo: '/cities/coimbatore.jpg',
    tagline: 'Marudhamalai & Hills',
    description: 'Palghat wind funnel effect, moderate rainshadow weather & localized showers.',
    weatherTypes: ['Palghat Funnel Wind', 'Rainshadow Showers', 'Sub-Ghats Thunder'],
    sensors: '12 AWS Stations · Agro Network',
  },
  {
    name: 'Madurai',
    aliases: ['madurai'],
    state: 'Tamil Nadu',
    zone: 'South',
    region: 'Vaigai River Plain',
    lat: 9.9252,
    lon: 78.1198,
    status: 'live',
    color: '#D97706',
    photo: '/cities/madurai.jpg',
    tagline: 'Meenakshi Amman Temple',
    description: 'Dry inland heat index, Vaigai basin hydrology & retreating monsoon showers.',
    weatherTypes: ['Dry Heat Alert', 'Retreating Monsoon', 'Vaigai Flood Watch'],
    sensors: '10 AWS Stations · Regional Sensor Grid',
  },
  // ── East & Central India ───────────────────────────────────────
  {
    name: 'Kolkata',
    aliases: ['kolkata', 'calcutta'],
    state: 'West Bengal',
    zone: 'East',
    region: 'Ganges Delta',
    lat: 22.5726,
    lon: 88.3639,
    status: 'live',
    color: '#0284C7',
    photo: '/cities/kolkata.jpg',
    tagline: 'Howrah Bridge & Victoria',
    description: 'Nor\'wester (Kalbaishakhi) severe storms, cyclone storm surge & Hooghly tidal surge.',
    weatherTypes: ['Kalbaishakhi Squalls', 'Cyclone Deluge', 'Tidal Waterlogging'],
    sensors: '24 AWS Stations · 2 Doppler Radars',
  },
  {
    name: 'Bhubaneswar',
    aliases: ['bhubaneswar', 'bhubaneshwar'],
    state: 'Odisha',
    zone: 'East',
    region: 'Eastern Coastal Plain',
    lat: 20.2961,
    lon: 85.8245,
    status: 'live',
    color: '#0891B2',
    photo: '/cities/bhubaneswar.jpg',
    tagline: 'Lingaraj & Temple City',
    description: 'Mahanadi delta flood discharge, high humidity heat index & cyclone early warning.',
    weatherTypes: ['Mahanadi Flood', 'Tropical Depression', 'Severe Coastal Gale'],
    sensors: '18 AWS Stations · Coastal Radar Mesh',
  },
  {
    name: 'Puri',
    aliases: ['puri'],
    state: 'Odisha',
    zone: 'East',
    region: 'Bay Coastal Shore',
    lat: 19.8135,
    lon: 85.8312,
    status: 'live',
    color: '#0284C7',
    photo: '/cities/puri.jpg',
    tagline: 'Jagannath & Golden Beach',
    description: 'Direct oceanic wave height, sea surface temperature anomalies & high gales.',
    weatherTypes: ['Oceanic Surge Wave', 'Coastal Cyclone Gale', 'Marine Inundation'],
    sensors: '8 Maritime Stations · Marine Buoys',
  },
  {
    name: 'Patna',
    aliases: ['patna'],
    state: 'Bihar',
    zone: 'East',
    region: 'Middle Ganges Plain',
    lat: 25.5941,
    lon: 85.1376,
    status: 'live',
    color: '#B45309',
    photo: '/cities/patna.jpg',
    tagline: 'Golghar & Ganges Basin',
    description: 'Ganges river flood forecasting, summer heatwaves & intense monsoon cloudbursts.',
    weatherTypes: ['Ganges Flood Warning', 'Intense Heatwave', 'Monsoon Downpour'],
    sensors: '15 AWS Stations · Flood Gauge Network',
  },
  {
    name: 'Ranchi',
    aliases: ['ranchi'],
    state: 'Jharkhand',
    zone: 'East',
    region: 'Chota Nagpur Plateau',
    lat: 23.3441,
    lon: 85.3096,
    status: 'live',
    color: '#059669',
    photo: '/cities/ranchi.jpg',
    tagline: 'Hundru Falls & Plateau',
    description: 'High-altitude convective lightning alerts, pleasant plateau climate & flash floods.',
    weatherTypes: ['Lightning Cluster Alert', 'Plateau Convection', 'Flash Reservoir Runoff'],
    sensors: '12 AWS Stations · Lightning Sensor Grid',
  },
  {
    name: 'Bhopal',
    aliases: ['bhopal'],
    state: 'Madhya Pradesh',
    zone: 'Central',
    region: 'Malwa Plateau',
    lat: 23.2599,
    lon: 77.4126,
    status: 'live',
    color: '#EA580C',
    photo: '/cities/bhopal.jpg',
    tagline: 'Upper Lake & City of Lakes',
    description: 'Lake basin hydrology, high summer thermal stress & thunderstorm clusters.',
    weatherTypes: ['Thermal Heatwave', 'Lake Watershed Surge', 'Plateau Thunderstorm'],
    sensors: '16 AWS Stations · Micro-Met Grid',
  },
  {
    name: 'Indore',
    aliases: ['indore'],
    state: 'Madhya Pradesh',
    zone: 'Central',
    region: 'Malwa High Plains',
    lat: 22.7196,
    lon: 75.8577,
    status: 'live',
    color: '#D97706',
    photo: '/cities/indore.jpg',
    tagline: 'Rajwada & Sarafa Hub',
    description: 'Urban flash precipitation drainage, evening Shab-e-Malwa breezes & heat stress.',
    weatherTypes: ['Urban Cloudburst', 'Malwa Squall Lines', 'Summer Heatwave'],
    sensors: '16 AWS Stations · Smart City Sensor Mesh',
  },
  {
    name: 'Raipur',
    aliases: ['raipur'],
    state: 'Chhattisgarh',
    zone: 'Central',
    region: 'Mahanadi Basin',
    lat: 21.2514,
    lon: 81.6296,
    status: 'live',
    color: '#DC2626',
    photo: '/cities/raipur.jpg',
    tagline: 'Vivekananda Sarovar',
    description: 'Mahanadi upper catchment rainfall, prolonged summer heatwave & severe dust storms.',
    weatherTypes: ['Extreme Heat Index', 'Upper Basin Downpour', 'Dust Convection'],
    sensors: '14 AWS Stations · Agro-Met Mesh',
  },
  // ── West India (Gujarat / Goa) ─────────────────────────────────
  {
    name: 'Ahmedabad',
    aliases: ['ahmedabad', 'amdavad'],
    state: 'Gujarat',
    zone: 'West',
    region: 'Sabarmati Basin',
    lat: 23.0225,
    lon: 72.5714,
    status: 'live',
    color: '#EA580C',
    photo: '/cities/ahmedabad.jpg',
    tagline: 'Atal Bridge & Sabarmati',
    description: 'Sabarmati river flood discharge, severe summer heat action plan telemetry.',
    weatherTypes: ['Heat Action Trigger', 'Urban Flood Alert', 'Dry Squalls'],
    sensors: '22 AWS Stations · Doppler Radar',
  },
  {
    name: 'Surat',
    aliases: ['surat'],
    state: 'Gujarat',
    zone: 'West',
    region: 'Tapi Estuary Coast',
    lat: 21.1702,
    lon: 72.8311,
    status: 'live',
    color: '#0284C7',
    photo: '/cities/surat.jpg',
    tagline: 'Tapi Estuary & Dumas',
    description: 'Tapi river discharge & Ukai dam flood telemetry, tidal water ingress monitoring.',
    weatherTypes: ['Ukai Dam Discharge', 'Tidal Surge Inundation', 'Heavy Coastal Rain'],
    sensors: '18 AWS Stations · Estuary Gauges',
  },
  {
    name: 'Panaji',
    aliases: ['panaji', 'goa', 'panjim'],
    state: 'Goa',
    zone: 'West',
    region: 'Konkan Coastline',
    lat: 15.4909,
    lon: 73.8278,
    status: 'live',
    color: '#0D9488',
    photo: '/cities/panaji.jpg',
    tagline: 'Mandovi & Goa Coastline',
    description: 'Mandovi and Zuari estuaries tidal surges, heavy monsoon deluges & marine gales.',
    weatherTypes: ['Heavy Monsoon Surge', 'Marine Squalls', 'Estuary Flood Stage'],
    sensors: '10 AWS Stations · Maritime Radar',
  },
  // ── Northeast India ────────────────────────────────────────────
  {
    name: 'Guwahati',
    aliases: ['guwahati', 'gauhati'],
    state: 'Assam',
    zone: 'Northeast',
    region: 'Brahmaputra Valley',
    lat: 26.1445,
    lon: 91.7362,
    status: 'live',
    color: '#059669',
    photo: '/cities/guwahati.jpg',
    tagline: 'Kamakhya & Brahmaputra',
    description: 'Brahmaputra mega-flood telemetry, torrential hill runoff & pre-monsoon squalls.',
    weatherTypes: ['Brahmaputra Flood Alert', 'Hill Flash Floods', 'Torrential Rain'],
    sensors: '16 AWS Stations · River Buoy Network',
  },
  {
    name: 'Shillong',
    aliases: ['shillong'],
    state: 'Meghalaya',
    zone: 'Northeast',
    region: 'Khasi Hills Plateau',
    lat: 25.5788,
    lon: 91.8933,
    status: 'live',
    color: '#0D9488',
    photo: '/cities/shillong.jpg',
    tagline: 'Umiam Lake & Khasi Ridge',
    description: 'World record rainfall corridor monitoring, deep cloudbursts & landslide hazards.',
    weatherTypes: ['Extreme Cloudburst', 'Landslide Vulnerability', 'Heavy Mist & Rain'],
    sensors: '10 High-Altitude Stations · Micro-Met',
  },
  {
    name: 'Agartala',
    aliases: ['agartala'],
    state: 'Tripura',
    zone: 'Northeast',
    region: 'Howrah River Basin',
    lat: 23.8315,
    lon: 91.2868,
    status: 'live',
    color: '#10B981',
    photo: '/cities/agartala.jpg',
    tagline: 'Ujjayanta Palace & Howrah',
    description: 'Howrah river trans-boundary flood early warning & heavy monsoon showers.',
    weatherTypes: ['Trans-Boundary Flood', 'Monsoon Downpour', 'High Humidity Index'],
    sensors: '8 AWS Stations · River Sensors',
  },
  {
    name: 'Imphal',
    aliases: ['imphal'],
    state: 'Manipur',
    zone: 'Northeast',
    region: 'Manipur River Valley',
    lat: 24.8170,
    lon: 93.9368,
    status: 'live',
    color: '#6366F1',
    photo: '/cities/imphal.jpg',
    tagline: 'Loktak Lake & Kangla',
    description: 'Imphal river flood stage, Loktak lake catchment telemetry & thunderstorm alerts.',
    weatherTypes: ['Valley Flood Warning', 'Catchment Inundation', 'Thunderstorm Gale'],
    sensors: '8 AWS Stations · Watershed Network',
  },
]

export const UPCOMING_CITIES = []

export const ALL_CITY_OPTIONS = [
  { value: '', label: 'All Cities Across India (38 Monitored Hubs)', group: 'all' },
  ...ACTIVE_CITIES.map((c) => ({
    value: c.name,
    label: `${c.name}, ${c.state} (${c.zone} India)`,
    city: c.name,
    state: c.state,
    zone: c.zone,
    status: 'live',
    color: c.color,
    photo: c.photo,
    group: 'active',
  })),
]

export function isUpcomingCity(cityName) {
  if (!cityName) return false
  const clean = cityName.trim().toLowerCase()
  return !ACTIVE_CITIES.some(
    (c) => c.name.toLowerCase() === clean || (c.aliases && c.aliases.includes(clean))
  )
}

export function getCityMetadata(cityName) {
  if (!cityName) return null
  const clean = cityName.trim().toLowerCase()
  return (
    ACTIVE_CITIES.find(
      (c) => c.name.toLowerCase() === clean || (c.aliases && c.aliases.includes(clean))
    ) || {
      name: cityName,
      state: 'India',
      zone: 'National',
      region: 'India Hub',
      lat: 20.5937,
      lon: 78.9629,
      status: 'live',
      color: '#0284C7',
      photo: '/city_mumbai.jpg',
      tagline: 'National Hub',
      description: 'Active weather monitoring and historical observation telemetry.',
      weatherTypes: ['Weather Events', 'Precipitation', 'Thermal Stress'],
      sensors: 'Live Doppler & Satellite Feeds',
    }
  )
}

export function normalizeCityName(cityName) {
  if (!cityName) return ''
  const clean = cityName.trim().toLowerCase()
  for (const c of ACTIVE_CITIES) {
    if (c.name.toLowerCase() === clean || (c.aliases && c.aliases.includes(clean))) {
      return c.name
    }
  }
  return cityName
}
